DROP TABLE SERVER IF EXISTS;
DROP TABLE STORAGES IF EXISTS;
DROP TABLE STORAGE_TIMEMARKS IF EXISTS;

CREATE TABLE SERVER (
    ID BIGINT NOT NULL,
    PARENT_ID BIGINT DEFAULT NULL,
    STORAGE_ID BIGINT NOT NULL,
    TIME_VIEW BIGINT DEFAULT NULL
);

CREATE TABLE STORAGES (
    ID BIGINT NOT NULL,
    PARENT_ID BIGINT
);

CREATE TABLE STORAGE_TIMEMARKS (
    STORAGE_ID BIGINT NOT NULL,
    TIMEVIEW_ID BIGINT,
    UUID VARCHAR(20) NOT NULL
);

insert into STORAGES values (1, null);

insert into SERVER values (1, null, 1, null);

insert into STORAGE_TIMEMARKS values (1, null, '1');
insert into STORAGE_TIMEMARKS values (1, null, '2');
insert into STORAGE_TIMEMARKS values (1, null, '3');
